#!/bin/sh
set -eu

if command -v /usr/bin/getent >/dev/null 2>&1; then
  exec /usr/bin/getent "$@"
fi

db="${1:-}"
key="${2:-}"

case "${db}" in
  group)
    grep -E "^${key}:" /etc/group
    ;;
  passwd)
    grep -E "^${key}:" /etc/passwd
    ;;
  *)
    exit 2
    ;;
esac
