#!/bin/sh

case "$1" in
  start)
    mkdir -p /var/empty
    chown root:root /var/empty
    chmod 0755 /var/empty
    ;;
  stop|restart|reload)
    ;;
  *)
    echo "Usage: $0 start"
    exit 1
    ;;
esac

exit 0
